import { render, screen, fireEvent, act } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import Desk from '../src/components/desk';
const API = 'https://api.clipdock.test';
function setup(){render(<Desk apiOrigin={API}/>);fireEvent.change(screen.getByLabelText('Enlace del video'),{target:{value:'https://www.youtube.com/watch?v=example'}});}
const inspection={token:'inspection-secret',title:'Mi video',thumbnail:null,platform:'youtube',duration:83,qualities:[720,0],has_audio:true};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status}));
async function inspect(){setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));await screen.findByText('Mi video');}
describe('Export desk',()=>{
 it('uses mocked API transport to export Original with quality zero',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation((input)=>{const path=String(input);if(path.endsWith('/api/inspect'))return response(inspection);if(path.endsWith('/api/jobs'))return response({id:'job-1',secret:'job-secret',status:'queued'});return response({id:'job-1',status:'completed',progress:100,download_url:'/api/files/job-1?secret=job-secret'});});await inspect();expect(fetcher).toHaveBeenCalledWith(API+'/api/inspect',expect.objectContaining({body:JSON.stringify({url:'https://www.youtube.com/watch?v=example',authorized:true})}));fireEvent.change(screen.getByLabelText('Calidad del video'),{target:{value:'0'}});fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));expect(await screen.findByRole('link',{name:'Descargar archivo'})).toHaveAttribute('href',API+'/api/files/job-1?secret=job-secret');expect(fetcher).toHaveBeenCalledWith(API+'/api/jobs',expect.objectContaining({body:JSON.stringify({token:'inspection-secret',authorized:true,format:'mp4',quality:0})}));});
 it('shows API errors and permits retry',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>response({error:{code:'UNSUPPORTED',message:'Este enlace no se puede descargar.'}},422));setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));expect(await screen.findByRole('alert')).toHaveTextContent('Este enlace no se puede descargar.');expect(screen.getByRole('button',{name:'Analizar enlace'})).toBeEnabled();});
 it('invalidates inspected metadata when the URL changes',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>response(inspection));await inspect();fireEvent.change(screen.getByLabelText('Enlace del video'),{target:{value:'https://x.com/user/status/123'}});expect(screen.queryByText('Mi video')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Preparar descarga'})).toBeDisabled();});
 it('ignores a stale inspection reply after changing URL',async()=>{let resolve!:(r:Response)=>void;vi.spyOn(globalThis,'fetch').mockImplementation(()=>new Promise(r=>{resolve=r;}));setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));fireEvent.change(screen.getByLabelText('Enlace del video'),{target:{value:'https://x.com/user/status/123'}});await act(async()=>{resolve(new Response(JSON.stringify(inspection)));});expect(screen.queryByText('Mi video')).not.toBeInTheDocument();});
 it('revoking rights clears inspection and cancels a pending export',async()=>{let resolve!:(r:Response)=>void;vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/api/inspect')?response(inspection):new Promise(r=>{resolve=r;}));await inspect();fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));fireEvent.click(screen.getByRole('checkbox'));await act(async()=>{resolve(new Response(JSON.stringify({id:'job-1',secret:'job-secret'})));});expect(screen.queryByText('Mi video')).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'Descargar archivo'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Analizar enlace'})).toBeDisabled();});
 it('bounds inspection time and aborts the request with a retryable message',async()=>{vi.useFakeTimers();let signal:AbortSignal|null|undefined;vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{signal=init?.signal;return new Promise(()=>{});});setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));await act(async()=>{await vi.advanceTimersByTimeAsync(45001);});expect(signal?.aborted).toBe(true);expect(screen.getByRole('alert')).toHaveTextContent('tardó demasiado');expect(screen.getByRole('button',{name:'Analizar enlace'})).toBeEnabled();vi.useRealTimers();});
 it('polls processing jobs and exposes a clean failure for unavailable audio',async()=>{vi.useFakeTimers();let polls=0;vi.spyOn(globalThis,'fetch').mockImplementation(input=>{if(String(input).endsWith('/api/inspect'))return response(inspection);if(String(input).endsWith('/api/jobs'))return response({id:'job-1',secret:'job-secret',status:'queued'});polls++;return response(polls===1?{status:'processing',progress:35}:{status:'failed',progress:35,error:{code:'NO_AUDIO',message:'Este video no contiene audio.'}});});setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));await act(async()=>{});expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow','35');await act(async()=>{await vi.advanceTimersByTimeAsync(2000);});expect(screen.getByRole('alert')).toHaveTextContent('Este video no contiene audio.');expect(screen.getByRole('button',{name:'Preparar descarga'})).toBeEnabled();vi.useRealTimers();});
 it('stops endless polling after ten minutes with a recoverable error',async()=>{vi.useFakeTimers();vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/api/inspect')?response(inspection):String(input).endsWith('/api/jobs')?response({id:'job-1',secret:'job-secret'}):response({status:'processing',progress:10}));setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));await act(async()=>{await vi.advanceTimersByTimeAsync(602000);});expect(screen.getByRole('alert')).toHaveTextContent('tiempo');expect(screen.getByRole('button',{name:'Preparar descarga'})).toBeEnabled();vi.useRealTimers();});
 it('does not expose a backend-supplied external download URL',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/api/inspect')?response(inspection):String(input).endsWith('/api/jobs')?response({id:'job-1',secret:'job-secret'}):response({status:'completed',progress:100,download_url:'https://evil.test/api/files/a'}));await inspect();fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));expect(await screen.findByRole('alert')).toHaveTextContent('descarga');expect(screen.queryByRole('link',{name:'Descargar archivo'})).not.toBeInTheDocument();});
 it('exports MP3 when audio is available',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/api/inspect')?response(inspection):String(input).endsWith('/api/jobs')?response({id:'job-1',secret:'job-secret'}):response({status:'completed',progress:100,download_url:'/api/files/a'}));await inspect();fireEvent.click(screen.getByRole('radio',{name:/MP3/}));fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));await screen.findByRole('link',{name:'Descargar archivo'});expect(fetcher).toHaveBeenCalledWith(API+'/api/jobs',expect.objectContaining({body:JSON.stringify({token:inspection.token,authorized:true,format:'mp3',quality:720})}));});
 it.each([{qualities:[720],has_audio:false,disabled:'MP3'},{qualities:[],has_audio:true,disabled:'MP4'}])('disables unavailable $disabled from actual inspected metadata',async config=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>response({...inspection,...config}));await inspect();expect(screen.getByRole('radio',{name:new RegExp(config.disabled)})).toBeDisabled();});
 it('aborts network requests when unmounted',async()=>{let signal:AbortSignal|null|undefined;vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{signal=init?.signal;return new Promise(()=>{});});const {unmount}=render(<Desk apiOrigin={API}/>);fireEvent.change(screen.getByLabelText('Enlace del video'),{target:{value:'https://youtu.be/example'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));unmount();expect(signal?.aborted).toBe(true);});
 it('uses a thumbnail-only preview and replaces broken images accessibly',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>response({...inspection,thumbnail:'https://i.ytimg.com/vi/a/default.jpg'}));await inspect();const image=screen.getByRole('img',{name:'Miniatura de Mi video'});expect(image).toHaveAttribute('referrerpolicy','no-referrer');expect(screen.getByText('Vista previa · miniatura')).toBeInTheDocument();fireEvent.error(image);expect(screen.getByText('Miniatura no disponible')).toBeInTheDocument();expect(screen.queryByRole('img')).not.toBeInTheDocument();});
 it('shows a truthful empty workspace and loading state without invented metadata',()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>new Promise(()=>{}));render(<Desk apiOrigin={API}/>);expect(screen.getByText('Tu video empieza con un enlace')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Preparar descarga'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Enlace del video'),{target:{value:'https://youtu.be/example'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));expect(screen.getByRole('button',{name:'Analizando enlace…'})).toBeDisabled();expect(screen.getByRole('status')).toHaveTextContent('Consultando');});
 it('invalidates an expired inspection and asks for a new analysis',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/api/inspect')?response(inspection):response({error:{code:'INVALID_TOKEN',message:'Inspección inválida o caducada.'}},400));await inspect();fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));expect(await screen.findByRole('alert')).toHaveTextContent('Vuelve a analizar');expect(screen.getByRole('button',{name:'Preparar descarga'})).toBeDisabled();expect(screen.getByRole('button',{name:'Analizar enlace'})).toBeEnabled();});
 it('clears polling timers when the workspace unmounts',async()=>{vi.useFakeTimers();vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/api/inspect')?response(inspection):String(input).endsWith('/api/jobs')?response({id:'job-1',secret:'job-secret'}):response({status:'processing',progress:10}));const {unmount}=render(<Desk apiOrigin={API}/>);fireEvent.change(screen.getByLabelText('Enlace del video'),{target:{value:'https://youtu.be/example'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Analizar enlace'}));await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:'Preparar descarga'}));await act(async()=>{});expect(vi.getTimerCount()).toBeGreaterThan(0);unmount();expect(vi.getTimerCount()).toBe(0);vi.useRealTimers();});
 it('requires explicit rights before inspecting',()=>{const fetcher=vi.spyOn(globalThis,'fetch');setup();expect(screen.getByRole('button',{name:'Analizar enlace'})).toBeDisabled();expect(fetcher).not.toHaveBeenCalled();});
});
