export const PLATFORMS = {youtube:'YouTube',tiktok:'TikTok',instagram:'Instagram',facebook:'Facebook',linkedin:'LinkedIn',x:'X'} as const;
export function safeDownload(value:unknown,api:string):string|null{if(typeof value!=='string'||!value||/[\\\\\s]/.test(value)||/%(?:2f|5c|25)/i.test(value))return null;try{const url=new URL(value,api);if(url.origin!==api||!url.pathname.startsWith('/api/')||url.username||url.password||url.hash)return null;return url.href;}catch{return null;}}
export function validateApiOrigin(value:string|undefined):string|null{if(!value||value.trim()!==value||/[\\\\\s]/.test(value))return null;try{const url=new URL(value);const local=['localhost','127.0.0.1','[::1]'].includes(url.hostname);if((url.protocol!=='https:'&&!(url.protocol==='http:'&&local))||url.username||url.password||url.pathname!=='/'||url.search||url.hash)return null;return url.origin;}catch{return null;}}
// Mirrors backend clipdock.network.CDNS; update both when changing policy.
export const THUMBNAIL_HOSTS=['i.ytimg.com','img.youtube.com','i9.ytimg.com','pbs.twimg.com','video.twimg.com'];
export function safeThumbnail(value:unknown):string|null{if(typeof value!=='string'||!value||/[\\\\\s]/.test(value))return null;try{const u=new URL(value);if(u.protocol!=='https:'||!THUMBNAIL_HOSTS.includes(u.host)||u.username||u.password||u.hash)return null;return u.href;}catch{return null;}}
export type Platform=keyof typeof PLATFORMS;
const domains:Record<Platform,string[]>={youtube:['youtube.com','youtu.be'],tiktok:['tiktok.com'],instagram:['instagram.com'],facebook:['facebook.com','fb.watch'],linkedin:['linkedin.com'],x:['x.com','twitter.com']};
export function detectPlatform(value:string):Platform|null{try{const url=new URL(value.trim());if(!['https:','http:'].includes(url.protocol)||url.username||url.password||url.port)return null;for(const [platform,hosts]of Object.entries(domains)){if(hosts.some(host=>url.hostname===host||url.hostname.endsWith('.'+host)))return platform as Platform;}return null;}catch{return null;}}
